### PR TITLE
JC-2199 Remove Spanish i18n

### PR DESCRIPTION
**Pull request by Pashokus**
I just removed Spanish from Language class and from Drop-down list in gui.
Also I change one of test(change Spanish to Russian in one test).

### CODE REVIEW

**Comment by Pashokus** [comment]
Of course

**Comment by Pashokus** [comment]
One justification of defect is "Currently only Russian-speaking audience uses our engines." Maybe I should set default language as Russian instead of English in case of Spanish language of user?

**Comment by ctapobep** [comment]
No, it's fine. All the population of the forum knows english and change the language on their own. So that' s fine.

**Comment by ctapobep** [comment]
@Pashokus it looks fine. Now please squash all the commits into 1 and we'll merge it.

**Comment by Pashokus** [comment]
@ctapobep done

**Comment by ctapobep** [comment]
Merged

**Pull request closed without merging**
