### PR TITLE
JC-1169 Configuring place to log

### PR DESCRIPTION
**Pull request by AnStrelnikov**
Now we can configure log4j.xml location by many ways.
Realization copied from POULPE-483 task.

### CODE REVIEW

**Comment by ctapobep** [comment]
@AnStrelnikov any updates?

**Comment by AnStrelnikov** [comment]
@ctapobep Sorry, I haven't saw this comments, I'll fix it as fast as I can.

**Comment by AnStrelnikov** [comment]
@ctapobep Now fixed

**Comment by ctapobep** [comment]
Ok, if you think it's ready to be merged, please squash both commits into 1 and I'll merge it.
Also, by default where the log will be placed? `TOMCAT/logs/jcommune`?

**Comment by AnStrelnikov** [comment]
I squashed commits. By default it uses log4.xml configuration file from jcommune-web-view project.

**Comment by ctapobep** [comment]
Merged

**Pull request closed without merging**
