### PR TITLE
[JC-2185][JC-2060] Long "Topic title" field

### PR DESCRIPTION
**Pull request by vps2**
- replaced the class name in the input field of the topic title
  from "span11" to "full-width".

### CODE REVIEW

**Comment by ctapobep** [comment]
Hi, @vps2, would mind fixing this issue for other topic types as well? For Code Reviews and Questions'n'Answers. The latter is installed as a plugin, so read the README for the information on how to install it.

**Comment by vps2** [comment]
Please tell me number of issues in the Jira.

**Comment by vps2** [comment]
Fixed the behavior of the topic fields in the Code Review Form.

If I understand correctly, issue JC-2060 is a problem with a topic title in the Questions'n'Answers plugin. Maybe its a separate branch to fix?

**Comment by ctapobep** [comment]
It's just someone was too lazy to specify other topic types :) I'll review the changes today, thanks!

**Comment by vps2** [comment]
If anything, I made the same correction to the Questions'n'Answers plugin, but so far it has not commited.

**Comment by ctapobep** [comment]
Then it's time to commit it :)

**Comment by vps2** [comment]
Commited.

**Comment by ctapobep** [comment]
Ok, looks good to me. Could you please squash the changes into one commit before I merge them?

**Comment by vps2** [comment]
Did one commit.

Can I after merging with the master branch to delete a branch vps2:JC-2185_Long_topic_title_field in my repository?

**Comment by ctapobep** [comment]
Merged!
Yes, of course you can remove the branch.

**Comment by vps2** [comment]
Please check the issue JC-2060, which is not closed in jira (status - reopened). Corrections were the same for all kinds of topics. Maybe something not finish?

**Comment by ctapobep** [comment]
Didn't notice the second issue. Moved it to QA.

**Pull request closed without merging**
