### PR TITLE
JC-2400 Search users that should be added to usergroup

### PR DESCRIPTION
**Pull request by evgeniycheban**
- FAB tool tip is absent. Fixed
- Change user adding to group pop up UI and functionality. Fixed
- Open the autocomplete list after entering any character. Fixed
- Check field length error message is shown for 51 symbols entered. Fixed

### CODE REVIEW

**Comment by oatkachenko** [comment]
Looks good, but I have one question. If user input only one character then error message displayed. Is it correct behaviour? I found only one mention about this case:
**Expected results:**

- The autocomplete list should not appear
- Sorting users in the autocomplete list should not start

Maybe, we should send request to server only after second character?

**Comment by evgeniycheban** [comment]
@oatkachenko I think you are right. I will update it.

**Comment by evgeniycheban** [comment]
Updated.

**Comment by oatkachenko** [comment]
thx, @ctapobep I have no questions.

**Pull request merged**
