### PR TITLE
master

### PR DESCRIPTION
**Pull request by shevarnadze**
JC-2208 Changed First/Last pagination buttons icon from "<" ">" to "<<" ">>"

### CODE REVIEW

**Comment by ctapobep** [comment]
The styles of the buttons look pretty ugly. Can you try using a different approach? Perhaps using unicode symbols instead of glyph icon. E.g. see how it's done here: http://getbootstrap.com/components/#pagination-default

**Comment by ctapobep** [comment]
@shevarnadze this looks much nicer. Have you checked that all the pages listed in the task are updated with your buttons? If yes, could you please squash your commits into 1 and I'll merge them.

**Comment by shevarnadze** [comment]
Squashed my 2 commit into 1, merge them, please.

**Comment by ctapobep** [comment]
Take a look at the Commits tab here in github - now you have 5 commits instead of 1.. Please google "git squash via reset soft".

**Comment by ctapobep** [comment]
@shevarnadze  Why did you close the PR?

**Comment by shevarnadze** [comment]
I was mistaken

**Comment by ctapobep** [comment]
@shevarnadze any progress on the squashing?

**Pull request merged**
