### PR TITLE
JC-1959 Lowercase beginning of the hints in new article page (EN, SPA)

### PR DESCRIPTION
**Pull request by wertklop**
JC-1959 Lowercase beginning of the hints in new article page (EN, SPA)
JC-2087 Lower-case text in message error

Added message error with uppercase beginning of the hints in new article page (EN, SPA). Both issues are equals

### CODE REVIEW

**Comment by ctapobep** [comment]
@wertklop what do you think about getting rid of _May not be empty_ and instead always show _Size should be ..._? It seems to me that these empty-error messages are not that informative..

**Comment by wertklop** [comment]
May be you are right, but error messages in issue has that text messages. If need other texts, i change it. Give me concrete text of messages, please

**Comment by ctapobep** [comment]
Ok, I've added a JIRA comment to consolidate all the error messages on all the forms.

**Comment by ctapobep** [comment]
@wertklop should I reassign this task to another person?

**Comment by ctapobep** [comment]
Was finished in different PRs.

**Pull request closed without merging**
