### PR TITLE
JC-2214 Get rid of Back button on Post/Topic Editing page

### PR DESCRIPTION
**Pull request by SurfVaporizer**
- back button has been removed from Post editing page
- back button has been removed from Topic editing page

### CODE REVIEW

**Comment by ctapobep** [comment]
@SurfVaporizer what about i18n for that button?

**Comment by SurfVaporizer** [comment]
@ctapobep Should I delete (label.back) field? Or what do you mean?
btw, field label.back=Back used in another parts of that project

**Comment by ctapobep** [comment]
Ok, if so there there is no need to delete that label.

**Comment by ctapobep** [comment]
Merged

**Pull request closed without merging**
