### PR TITLE
JC-2104 Add condition which check type of topic

### PR DESCRIPTION
**Pull request by NCNecros**
I added popup text for russian, spanish and english interfaces

### CODE REVIEW

**Comment by ctapobep** [comment]
@NCNecros could you please ask for help in translations in JIRA comments? I'd like to have one commit that fixes this issue, no need to split the fix into several commits.

**Comment by ctapobep** [comment]
Also, because of bugs in JIRA I had to delete that ticket. I've created a replacement: http://jira.jtalks.org/browse/JC-2104 Please update the commit message with the new one.

**Comment by jarey** [comment]
@NCNecros @ctapobep I've just replied on the Jira issue, with the Spanish translation. 
Please let me know if i can be of any help.

**Comment by NCNecros** [comment]
@jarey Thanks.

**Comment by ctapobep** [comment]
Thanks buddy )

**Comment by ctapobep** [comment]
@NCNecros could you please also re-phrase your commit message, from it I wouldn't understand its ultimate purpose.

**Comment by NCNecros** [comment]
I add Ukrainian languages. Please check PR.

**Comment by ctapobep** [comment]
Yes, it's fine, thanks. But commit message still needs a correction.

**Comment by NCNecros** [comment]
How?

**Comment by ctapobep** [comment]
Do you mean technically? It's commit --amend.

If you don't know _what_ to write - well, that's what you need to figure out yourself ;) Right now it's not clear from commit message what was actually done and what value it has to users.

**Comment by NCNecros** [comment]
it looks fine now?

**Comment by ctapobep** [comment]
Nope, the first line must be clear to others. Something like `JC-2104 Update Delete Code Review dialog message`. And in the next lines you may explain about the condition if you think it's worth it.

**Comment by NCNecros** [comment]
Done.

**Comment by ctapobep** [comment]
Thanks, let's merge it when new iteration starts (in several days). Please move the task to done.

**Comment by ctapobep** [comment]
merged

**Pull request closed without merging**
