### PR TITLE
JC-2018 text of "Recent activity" and "Search results" have two rows

### PR DESCRIPTION
**Pull request by vps2**
- replaced classes responsible for a dimension elements "div".

### CODE REVIEW

**Comment by vps2** [comment]
Please tell me: when you fix bugs in UI, can I use HTML5 tags (e.g., autofocus) or should I stick with HTML4?

**Comment by ctapobep** [comment]
@dsdolzhenko what do you think?

**Comment by dsdolzhenko** [comment]
@ctapobep @vps2, I think, there is no reason not to use HTML5 features today. Moreover, we already use them in this project.

**Comment by vps2** [comment]
Understood. 
Thanks for the reply.

**Pull request merged**
