### PR TITLE
JC-2097 Change pluginHandlerMethods to ConcurrentHashMap

### PR DESCRIPTION
**Pull request by NCNecros**

### CODE REVIEW

**Comment by mixas27** [comment]
@ctapobep, Let me explain you. Resolving of handler has next flow:
```java
  pluginHandlerMethods.clear();
  pluginLoader.reloadPlugins(new TypeFilter(WebControllerPlugin.class));
  handlerMethod = findHandlerMethod(key);
```
First of all we clear old map of handlers (line 1). This is necessary for case if plugin version was updated and some handlers was changed or removed.
At line 2 we reload all `WebControllerPlugins`. Each `WebControllerPlugin` gives its handler to Plugin handler mapping (puts to `pluginHandlerMethods` map) during configuration.
At line 3 we search handler method in `pluginHandlerMethods` map.

I think, next scenario is possible:
1. Thread 1 clears `pluginHandlerMethods` map
2. Thread 1 reloads plugin and fills `pluginHandlerMethods` map
3. Thread 2 clears `pluginHandlerMethods` map
4. Thread 1 search handler in empty map

`synchronized` block should prevent it

**Comment by ctapobep** [comment]
@mixas27, @NCNecros we either need to mitigate the problem by introducing a concurrent collection or we can postpone this issue until we refactor how plugins work. In either case it's good that we've localized the issue.

**Comment by NCNecros** [comment]
@ctapobep, what should I do now?

**Comment by ctapobep** [comment]
Choose your destiny! Have you tried the partial fix with concurrent collections yet?

**Comment by NCNecros** [comment]
@ctapobep, I think the partial fix with concurrent collections will be enough.

**Comment by ctapobep** [comment]
@NCNecros did you test it? How much does the percentage of failures decrease?

**Comment by NCNecros** [comment]
I am sorry for the delay. With this correction, I was not able to reproduce the bug.

**Comment by ctapobep** [comment]
@NCNecros you mean with Concurrent Collections? If so, could you please update the PR?

**Comment by NCNecros** [comment]
@ctapobep , i mean with current changes. Should  I rewriting used the Concurrent Collections?

**Comment by ctapobep** [comment]
@NCNecros current changes are bad from performance perspective. Yes, please try concurrent collections as an alternative.

**Comment by NCNecros** [comment]
@ctapobep, please review. After this change, the bug is not reproduced.

**Comment by ctapobep** [comment]
@NCNecros ok, looks cool, could you please squash the commits before we merge it into master?

**Comment by NCNecros** [comment]
@ctapobep, done.

**Comment by NCNecros** [comment]
@ctapobep, I combined them.

**Comment by ctapobep** [comment]
Merged

**Pull request closed without merging**
