### PR TITLE
JC-1998 Wrong error message below the "New Password" field

### PR DESCRIPTION
**Pull request by vps2**
- added a message attribute of the annotation Size (the newUserPassword
  field of the UserSecurityDto class)

### CODE REVIEW

**Comment by ctapobep** [comment]
No need to put underscores in the commit message - it's not a branch or a tag name :)

**Comment by vps2** [comment]
Ok :)

**Comment by ctapobep** [comment]
Reviewed - the solution doesn't comply with the expected result. Instead of using custom labels for every field we want to use a single label for all of the fields. What we need to do is to change the label to the common one (the one that all the other fields are using) and then remove `user.password.length_constraint_violation` at all from all the files.

**Comment by vps2** [comment]
In the resource bundle "ValidationMessages" has label  "length.constraint" with the following content:

- eng -> "Length must be between {min} and {max} symbols"
- rus -> "Длина должна быть между 1 и 50 символами"
- urk -> "Довжина повинна бути від 1 до 50 символів"

So, we get the expected result. This is the right label that will be used by all other fields?

**Comment by ctapobep** [comment]
Yap

**Comment by vps2** [comment]
Sorry, but I can't understand You.
Can i something not so wrote?

**Comment by ctapobep** [comment]
You should use the generic message, `length.constraint` seems to be the right one.

**Comment by vps2** [comment]
It is now clear. 
Thank you.

**Comment by vps2** [comment]
You probably messed up the second letter in the word above (https://github.com/jtalks-org/jcommune/pull/129#issuecomment-145966736). According to the dictionary, this word a different meaning.

**Comment by ctapobep** [comment]
They can use any letter there: yap, yup, yep, etc. In English there are no boundaries :)

**Comment by vps2** [comment]
Well then I misunderstood. :)

**Pull request closed without merging**
