### PR TITLE
JC-2167 Incorrect English translation for delete question pop-up

### PR DESCRIPTION
**Pull request by Chichavl**
Renamed message constants.

### CODE REVIEW

**Comment by mixas27** [comment]
Merged. Thank you

**Comment by ctapobep** [comment]
@Chichavl it appeared that QA requested the change for all 3 topic types while you changed only one of them. Please see [comments](http://jira.jtalks.org/browse/JC-2167?focusedCommentId=28914&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-28914). Will you be able to create another PR with additional changes to finally close this bug?

**Comment by Chichavl** [comment]
Yes, i will, sorry for inconvenience.
21 апр. 2015 г. 4:03 PM пользователь "Stanislav Bashkyrtsev" <
notifications@github.com> написал:

**Comment by Chichavl** [comment]
Created pull https://github.com/jtalks-org/jcommune/pull/74

**Pull request closed without merging**
