### PR TITLE
Jc 2149

### PR DESCRIPTION
**Pull request by AlbertLysenco**
English/Spanish translation in "Add link" editor of "External link editor"

### CODE REVIEW

**Comment by ctapobep** [comment]
@AlbertLysenco you have two commits for different tasks in this PR. In order to have separate PRs you have to introduce changes in different branches.

**Comment by AlbertLysenco** [comment]
Sorry, have left only one commit

**Comment by ctapobep** [comment]
Thanks. To be merged in 3.1

**Comment by ctapobep** [comment]
Merged

**Pull request closed without merging**
